using Meow.Core.Models;

namespace Meow.Core.Services;

/// <summary>
/// Implementation of project initialization service
/// </summary>
public class ProjectService : IProjectService
{
    private readonly IConfigService _configService;

    /// <summary>
    /// Creates a new instance of ProjectService
    /// </summary>
    /// <param name="configService">Configuration service instance</param>
    public ProjectService(IConfigService configService)
    {
        _configService = configService;
    }

    /// <inheritdoc />
    public async Task<bool> InitializeMasmProjectAsync(string name, string path, string? author = null)
    {
        try
        {
            // Create project directory if it doesn't exist
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            // Create subdirectories
            Directory.CreateDirectory(Path.Combine(path, "src"));
            Directory.CreateDirectory(Path.Combine(path, "tests"));
            Directory.CreateDirectory(Path.Combine(path, "build"));

            // Create meow.yaml configuration
            var config = new MeowConfig
            {
                Name = name,
                Version = "0.1.0",
                Description = $"A {name} MASM project",
                Type = "masm",
                Main = "src/main.masm",
                Build = new BuildConfig
                {
                    Mode = "debug",
                    Output = "build",
                    Target = "default",
                    Incremental = true
                }
            };

            if (!string.IsNullOrEmpty(author))
            {
                config.Authors.Add(author);
            }

            await _configService.SaveConfigAsync(config, Path.Combine(path, "meow.yaml"));

            // Create a starter MASM file
            var masmContent = GetMasmTemplate(name);
            await File.WriteAllTextAsync(Path.Combine(path, "src", "main.masm"), masmContent);

            // Create a README
            var readmeContent = GetReadmeTemplate(name, "masm");
            await File.WriteAllTextAsync(Path.Combine(path, "README.md"), readmeContent);

            // Create .gitignore
            var gitignoreContent = GetGitignoreTemplate();
            await File.WriteAllTextAsync(Path.Combine(path, ".gitignore"), gitignoreContent);

            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Initialize a project for the specified compiler/language
    /// </summary>
    public async Task<bool> InitializeProjectAsync(string name, string path, string compiler = "masm", string? author = null)
    {
        try
        {
            // Create project directory if it doesn't exist
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            // Create subdirectories
            Directory.CreateDirectory(Path.Combine(path, "src"));
            Directory.CreateDirectory(Path.Combine(path, "tests"));
            Directory.CreateDirectory(Path.Combine(path, "build"));

            // Determine main file and templates based on compiler
            string type = compiler.ToLowerInvariant();
            string mainFile;
            string mainContent;
            string description = $"A {name} {type} project";

            switch (type)
            {
                case "c":
                    mainFile = "src/main.c";
                    mainContent = $"/* {name} - C main\n   Generated by Meow */\n#include <stdio.h>\nint main(void) {{ printf(\"Hello from {name}!\\n\"); return 0; }}\n";
                    break;
                case "cpp":
                    mainFile = "src/main.cpp";
                    mainContent = $"// {name} - C++ main\n// Generated by Meow\n#include <iostream>\nint main() {{ std::cout << \"Hello from {name}!\" << std::endl; return 0; }}\n";
                    break;
                case "fortran":
                    mainFile = "src/main.f90";
                    mainContent = $"! {name} - Fortran main\n! Generated by Meow\nprogram main\n  print *, \"Hello from {name}!\"\nend program main\n";
                    break;
                case "masm":
                    mainFile = "src/main.masm";
                    mainContent = GetMasmTemplate(name);
                    break;
                case "sharpir":
                    mainFile = "src/main.sir";
                    mainContent = $"// {name} - SharpIR main\n// Generated by Meow\n\nprint \"Hello from {name}!\"\n";
                    break;
                case "uhigh":
                    mainFile = "src/main.uh";
                    mainContent = $"// {name} - Uhigh main\n// Generated by Meow\n\n; Your uhigh code here\n";
                    break;
                case "objectfortran":
                    mainFile = "src/main.f90";
                    mainContent = $"! {name} - ObjectFortran main\n! Generated by Meow\nprogram main\n  print *, \"Hello from {name}!\"\nend program main\n";
                    break;
                case "objectivepascal":
                    mainFile = "src/main.pas";
                    mainContent = $"// {name} - ObjectivePascal main\nprogram {name};\nbegin\n  writeln('Hello from {name}!');\nend.\n";
                    break;
                default:
                    mainFile = "src/main.txt";
                    mainContent = $"// {name} - Main file for {type}\n";
                    break;
            }

            var config = new MeowConfig
            {
                Name = name,
                Version = "0.1.0",
                Description = description,
                Type = type,
                Main = mainFile,
                Build = new BuildConfig
                {
                    Mode = "debug",
                    Output = "build",
                    Target = "default",
                    Incremental = true,
                    Compiler = type,
                    Objdir = "build/obj"
                }
            };

            if (!string.IsNullOrEmpty(author))
            {
                config.Authors.Add(author);
            }

            await _configService.SaveConfigAsync(config, Path.Combine(path, "meow.yaml"));

            // Create the main file for the chosen compiler
            await File.WriteAllTextAsync(Path.Combine(path, mainFile), mainContent);

            // Create a README
            var readmeContent = GetReadmeTemplate(name, type);
            await File.WriteAllTextAsync(Path.Combine(path, "README.md"), readmeContent);

            // Create .gitignore
            var gitignoreContent = GetGitignoreTemplate();
            await File.WriteAllTextAsync(Path.Combine(path, ".gitignore"), gitignoreContent);

            return true;
        }
        catch
        {
            return false;
        }
    }

    /// <inheritdoc />
    public bool IsExistingProject(string path)
    {
        return _configService.ConfigExists(Path.Combine(path, "meow.yaml"));
    }

    private static string GetMasmTemplate(string name)
    {
        return $@"; {name} - Main Entry Point
; This is a starter MASM (MicroAssembly) project created with Meow

; Program entry point
lbl main
    ; Your code here
    hello: db ""Hello from {name}!""
    push $hello
    call #print
    hlt

; Print function
lbl print
    pop RAX
    out 1 $RAX
    ret
";
    }

        private static string GetReadmeTemplate(string name, string type)
        {
                var lang = type.ToUpperInvariant();
                return $"# {name}\n\nA {type} project created with Meow.\n\n## Getting Started\n\n### Build\nmeow build\n\n### Run\nmeow run\n\n### Test\nmeow test\n\n## About {lang}\n\nThis project was scaffolded for the {type} toolchain. Replace this text with language-specific notes as needed.\n\n## Dependencies\n\nDependencies are managed through PurrNet. Add them in meow.yaml:\n\ndependencies:\n  example-lib: \"^1.0.0\"\n\nThen run:\nmeow install\n";
        }

    private static string GetGitignoreTemplate()
    {
        return @"# Build outputs
build/
*.out
*.exe

# Dependencies
.meow/
node_modules/

# IDE
.vscode/
.idea/
*.swp
*~

# OS
.DS_Store
Thumbs.db
";
    }
}
